name: Expressions and Context
on: [push, workflow_dispatch]

jobs:
    usding-expressions-and-contexts:
        runs-on: ubutun-latest
        steps:
           - name: expressions
             id: expressions
             run: |
              echo ${{ 1 }}
              echo ${{ 'This is a string' }}
              echo ${{ null }}
              echo ${{ true }}
              echo ${{ 1 > 2 }}
              echo ${{ 'string' == 'string' }}
              echo ${{ true && false }}
              echo ${{ true || (false && true) }}
           - name: Dump Contexts
             run: |
              echo '${{ toJson(github) }}'
              echo '${{ toJson(job) }}'
              echo '${{ toJson(secrets) }}'
              echo '${{ toJson(steps) }}'
              echo '${{ toJson(runner) }}'